---
  # Install packages
  - name: install packages needed to monitor host
    apt: name={{ item }} state=present
    with_items:
      - check-mk-agent
      - nagios-plugins-basic

  # Creating files and directories
  - name: create /etc/check_mk directory
    file: state=directory recurse=yes
          dest=/etc/check_mk
          owner=root group=root

  - name: create mrpe.cfg
    copy: dest=/etc/check_mk/mrpe.cfg force=no
          content='# managed by ansible\n'
          owner=root group=root mode=0644

  - name: add run-agent.sh script used as check-mk shell
    copy: dest=/usr/lib/check_mk_agent/run-agent.sh
          src=../../files/check_mk/run-agent.sh
          owner=root group=root mode=0755

  - name: add modified check_mk_agent binary
    copy: dest=/usr/bin/check_mk_agent
          src=../../files/check_mk/check_mk_agent force=yes
          owner=root group=root mode=0755

  # Manage users
  - name: create check-mk user
    user: name=check-mk groups=ssh
          home=/usr/lib/check_mk_agent
          shell=/usr/lib/check_mk_agent/run-agent.sh

  - name: add SSH key to check-mk user
    authorized_key: user=check-mk manage_dir=true state=present
                    key="{{ lookup('file', 'check_mk/authorized_keys') }}"

  # Adding sudo permissions
  - name: adding sudo permissions for check-mk user
    lineinfile: "dest=/etc/sudoers state=present regexp='^check-mk'
                line='check-mk ALL=(ALL) NOPASSWD: /usr/bin/check_mk_agent'"


  # TODO: snippet should be removed if everything is deployed ones
  #       check_record script should be only deployed on encoder
  - name: remove check_recording script from mrpe.cfg for non encoder
    lineinfile: dest=/etc/check_mk/mrpe.cfg regexp='^RECORDING'
                line='RECORDING /usr/local/bin/check_recording /video'
                state=absent
    when: not ansible_hostname | match("encoder\d+")

  # TODO: snippet should be removed if everything is deployed ones
  #       check_record script should be only deployed on encoder
  - name: remove check_recording script on non encoder
    file: dest=/usr/local/bin/check_recording state=absent
    when: not ansible_hostname | match("encoder\d+")
