---
  # install general mixer packages
  - name: install packages required to be a OBS studio mixer
    apt: 
      pkg:
        - chromium
        - fonts-roboto
        - mate-desktop-environment
        - obs-studio 
        - x11vnc
        - x11-xserver-utils
        - xserver-xorg
        - xserver-xorg-video-all
        - xserver-xorg-video-ast
        - xterm
      state: latest

