---
  - name: create /opt/voc/share/ diretcory
    file: dest=/opt/voc/share/ state=directory
          owner=root group=root mode=0755

  - name: add overlay image
    copy: src={{ item }}
          dest=/opt/voc/share/overlay_sd.png
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/overlay.png"
      - "../../../artwork/{{ event.acronym }}/overlay.png"
      - "artwork/default-overlay.png"

  - name: add hd-overlay image
    copy: src={{ item }}
          dest=/opt/voc/share/overlay_hd.png
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/overlay_hd.png"
      - "../../../artwork/{{ event.acronym }}/overlay_hd.png"
      - "artwork/default-overlay_hd.png"

  - name: add nostream image
    copy: src={{ item }}
          dest=/opt/voc/share/nostream.png
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/nostream.png"
      - "../../../artwork/{{ event.acronym }}/nostream.png"
      - "artwork/default-nostream.png"
