---
  # see packages.yml for gstreamer package installation

  # directories & code
  - name: create voctomix directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /video/
      - /video/intros/
      - /video/music/
      - /opt/voctomix/scripts/
      - /opt/voctomix/release/

  - name: checkout voctomix release
    git: repo=https://c3voc.de/git/voctomix
         dest=/opt/voctomix/release/
         version=0.2
         force=yes
         accept_hostkey=yes



  # decklink sources
  - name: list decklink input devices
    shell: ffmpeg -hide_banner -f decklink -list_devices 1 -i dummy 2>&1 | grep decklink | grep "'" | cut -d"'" -f2
    register: decklink_devices
    changed_when: False

  - name: list decklink input device formats
    shell: ffmpeg -hide_banner -f decklink -list_formats 1 -i '{{ item.1 }}' 2>&1 | grep '1920x1080 at 25000/1000 fps (interlaced' | cut -f2 -d'	'
    register: decklink_formats
    with_indexed_items: decklink_devices.stdout_lines

  - name: calculating sources
    set_fact:
      number_decklink: "{{ decklink_devices.stdout_lines | length }}"
      number_cameras: "{{ [1, decklink_devices.stdout_lines | length] | max }}"

  - name: print source information
    debug: msg="Found {{ number_decklink }} Decklink Inputs ({{ decklink_devices.stdout_lines }}), Configuring Voctocore with {{ number_cameras }} Camera-Sources (Minumum=1)"

  - name: create decklink-source scripts
    template: src=voctomix-scripts/decklink-source.sh.j2
              dest=/opt/voctomix/scripts/decklink-source-{{ item.0 + 1 }}.sh
              mode=0755 owner=root group=root
    with_indexed_items: decklink_devices.stdout_lines

  - name: create decklink-source systemd-units
    template: src=systemd-units/voctomix-decklink-source.service.j2
              dest=/etc/systemd/system/voctomix-decklink-source-{{ item.0 + 1 }}.service
              mode=0644 owner=root group=root
    with_indexed_items: decklink_devices.stdout_lines

  - name: enable decklink-source services
    service: name=voctomix-decklink-source-{{ item.0 + 1 }}
             enabled=yes
    with_indexed_items: decklink_devices.stdout_lines



    # grabber source source
  - name: create grabber-source script
    template: src=voctomix-scripts/grabber-source.sh.j2
              dest=/opt/voctomix/scripts/grabber-source.sh
              mode=0755 owner=root group=root

  - name: create grabber-source systemd-unit
    template: src=systemd-units/voctomix-grabber-source.service.j2
              dest=/etc/systemd/system/voctomix-grabber-source.service
              mode=0644 owner=root group=root

  - name: enable grabber-source service
    service: name=voctomix-grabber-source
             enabled=yes



  # pause source
  - name: uploading default pause-loop
    copy: src=artwork/default-pause.ts
          dest=/video/intros/default-pause.ts
          mode=0644 owner=root group=root

  - name: creating default pause-loop symlink
    file: src=default-pause.ts
          dest=/video/intros/pause.ts
          state=link
          mode=0644 owner=root group=root

  - name: create pause-source script
    template: src=voctomix-scripts/pause-source.sh.j2
              dest=/opt/voctomix/scripts/pause-source.sh
              mode=0755 owner=root group=root

  - name: create pause-source systemd-unit
    template: src=systemd-units/voctomix-pause-source.service.j2
              dest=/etc/systemd/system/voctomix-pause-source.service
              mode=0644 owner=root group=root

  - name: enable pause-source service
    service: name=voctomix-pause-source
             enabled=yes



    # pause music source
  - name: uploading default music-files
    copy: src=artwork/pause-music/
          dest=/video/pause-music/
          mode=0644 directory_mode=0755 owner=root group=root

  - name: create music-source script
    template: src=voctomix-scripts/music-source-from-folder.py.j2
              dest=/opt/voctomix/scripts/music-source-from-folder.py
              mode=0755 owner=root group=root

  - name: create music-source systemd-unit
    template: src=systemd-units/voctomix-music-source.service.j2
              dest=/etc/systemd/system/voctomix-music-source.service
              mode=0644 owner=root group=root

  - name: enable music-source service
    service: name=voctomix-music-source
             enabled=yes



    # bgloop source
  - name: uploading default bgloop
    copy: src=artwork/default-bgloop.ts
          dest=/video/intros/bgloop.ts
          mode=0644 directory_mode=0755 owner=root group=root

  - name: create bgloop script
    template: src=voctomix-scripts/bgloop-source.sh.j2
              dest=/opt/voctomix/scripts/bgloop-source.sh
              mode=0755 owner=root group=root

  - name: create bgloop systemd-unit
    template: src=systemd-units/voctomix-bgloop-source.service.j2
              dest=/etc/systemd/system/voctomix-bgloop-source.service
              mode=0644 owner=root group=root

  - name: enable bgloop service
    service: name=voctomix-bgloop-source
             enabled=yes



  # voctocore configuration
  - name: create voctocore config
    template: src=voctomix-config/voctocore-config.ini.j2
              dest=/opt/voctomix/voctocore-config.ini
              mode=0644 owner=root group=root

  # voctocore service
  - name: create voctocore systemd-unit
    template: src=systemd-units/voctomix-voctocore.service.j2
              dest=/etc/systemd/system/voctomix-voctocore.service
              mode=0644 owner=root group=root

  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: enable & start voctocore service when in voctomix-mode
    service: name=voctomix-voctocore
             enabled=yes
             state=started
    when: encodermode is defined and encodermode == 'hd-voctomix'

  - name: disable & start voctocore service when not in voctomix-mode
    service: name=voctomix-voctocore
             enabled=no
             state=stopped
    when: encodermode is not defined or encodermode != 'hd-voctomix'
