---
 - include: general.yml
 - include: packages.yml
 - include: artwork.yml
 - include: sdisource.yml
 - include: sdi-script.yml
 - include: dvsink.yml
 - include: grabbersource.yml
 - include: pausesource.yml
 - include: nginx.yml
 - include: samba.yml
 - include: rc.local.yml
