---
  # pausesource configuration
  - name: create service directory for pausesource
    file: dest=/etc/service/pausesource state=directory
          owner=root group=root

  - name: create runit grabbersource file
    template: dest=/etc/service/pausesource/run
              src=pausesource/run.j2
              owner=root group=root mode=0755


  - name: create runit pausesource-down-file file when not in dvsplit-mode
    file: dest=/etc/service/pausesource/down
          state=touch
          owner=root group=root mode=0655
    when: encodermode is defined and encodermode != 'sd-dvswitch'

  - name: remove runit pausesource-down-file file when in dvsplit-mode
    file: dest=/etc/service/pausesource/down
          state=absent
    when: encodermode is not defined or encodermode == 'sd-dvswitch'
