---
  # see packages.yml for sdisource package installation

  # sdisource configuration
  - name: create service directory for sdisource
    file: dest=/etc/service/{{ item }} state=directory
    with_items:
      - sdisource-0
      - sdisource-1

  - name: create runit sdisource file for each schwarzemagie-capture card
    template: dest=/etc/service/{{ item.name }}/run
              src=sdisource/run.j2
              owner=root group=root mode=0755
    with_items:
      - { id: 0, placement: 2, name: "sdisource-0" }
      - { id: 1, placement: 3, name: "sdisource-1" }

  - name: create runit sdisource-down-file file when not in dvsplit-mode
    file: dest=/etc/service/{{ item.name }}/down
          state=touch
          owner=root group=root mode=0655
    when: encodermode is defined and encodermode != 'sd-dvswitch'
    with_items:
      - { name: "sdisource-0" }
      - { name: "sdisource-1" }

  - name: remove runit sdisource-down-file file when in dvsplit-mode
    file: dest=/etc/service/{{ item.name }}/down
          state=absent
    when: encodermode is not defined or encodermode == 'sd-dvswitch'
    with_items:
      - { name: "sdisource-0" }
      - { name: "sdisource-1" }
