- name: check if cdn-app(UID:1001,GID:100) exists
  shell: grep "cdn-app:x:1001:100::/home/uploaders/cdn-app:/bin/sh" /etc/passwd
- name: check if ftp(UID:1022,GID:100) exists
  shell: grep "ftp:x:1022:100::/home/ftp:/bin/false" /etc/passwd
- name: check if cdn-app(UID:1022,GID:100) exists
  shell: grep "uploaders:x:1001:" /etc/group