---
# set up distribution icecast
  - name: realise icedist config
    copy: dest=/etc/icecast2/icedist.xml
          src=icedist/icedist.xml
          owner=icecast2 group=icecast mode=0660
    notify: restart icedist

  - name: create icedist systemd unit
    copy: src=icedist/icedist.service
          dest=/etc/systemd/system/icedist.service
          mode=0644 owner=root group=root

  - name: create icedist logging directory
    file: dest=/var/log/icedist
          state=directory
          mode=755 owner=icecast2 group=icecast

  - name: enable icedist on boot
    service: name=icedist.service
             enabled=yes
             state=started
