
# transcoder
- name: Create parent directory for transcoder scripts
  file: path=/opt/transcoder2 state=directory mode=0755

- name: Create config directory for transcoder scripts
  file: path=/opt/transcoder2/config state=directory mode=0755

- name: Install transcoder scripts
  git:
    repo: https://github.com/voc/transcoding
    dest: /opt/transcoder2/scripts
    update: yes

- name: Configure transcoder scripts
  template: src=transcoder/config.py.j2 dest=/opt/transcoder2/scripts/config.py

- name: Install systemd template service
  copy: src=transcode.service dest=/etc/systemd/system/transcode@.service mode=0755

- name: Install systemd template target
  copy: src=transcode.target dest=/etc/systemd/system/transcode@.target mode=0755

- name: Force systemd reload
  systemd: daemon_reload=yes

# upload-proxy
- name: Create directory for upload-proxy binary
  file: path=/opt/upload-proxy state=directory mode=0755

- name: Install upload-proxy binary
  copy: src="upload-proxy/upload-proxy" dest="/opt/upload-proxy/upload-proxy" mode=0755

- name: Create config directory for upload-proxy
  file: path=/etc/upload-proxy state=directory mode=0755

- name: Configure upload-proxy
  template: src=upload-proxy/config.toml.j2 dest=/etc/upload-proxy/config.toml

- name: Install systemd unit for upload-proxy
  copy: src=upload-proxy/upload-proxy.service dest=/etc/systemd/system/upload-proxy.service mode=0755

- name: Enable and start systemd unit for upload-proxy
  systemd: name=upload-proxy enabled=yes state=started daemon_reload=yes

# stream-api
- name: Create directory for stream-api binary
  file: path=/opt/stream-api state=directory mode=0755

- name: Install stream-api binary
  copy: src="stream-api/stream-api" dest="/opt/stream-api/stream-api" mode=0755

- name: Create config directory for stream-api
  file: path=/etc/stream-api state=directory mode=0755

- name: Configure stream-api
  template: src=stream-api/config.yml.j2 dest=/etc/stream-api/config.yml

- name: Install systemd unit for stream-api
  copy: src=stream-api/stream-api.service dest=/etc/systemd/system/stream-api.service mode=0755

- name: Enable and start systemd unit for stream-api
  systemd: name=stream-api enabled=yes state=started daemon_reload=yes

