---
  - include: ../../../register/bin_path.yml
  - include: ../../letsencrypt/main.yml domain={{ ansible_fqdn }}
  - include: nginx.yml
  - include: php.yml
  - include: streaming_website.yml
  - include: haproxy.yml
  - include: ocsp.yml
  - include: sysctl.yml
  - include: iptables.yml
