---
  - name: create /opt/voc/share/ directory
    file: dest=/opt/voc/share/ state=directory
          owner=root group=root mode=0755

  - name: add hd-overlay image
    copy: src={{ item }}
          dest=/opt/voc/share/overlay_hd.png
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/overlay_hd.png"
      - "../../../artwork/{{ event.acronym }}/overlay_hd.png"
      - "artwork/default-overlay.png"

  - name: add slides-overlay image
    copy: src={{ item }}
          dest=/opt/voc/share/overlay_slides.png
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/overlay_slides.png"
      - "../../../artwork/{{ event.acronym }}/overlay_slides.png"
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/overlay_hd.png"
      - "../../../artwork/{{ event.acronym }}/overlay_hd.png"
      - "artwork/default-overlay.png"

  - name: uploading background-loop
    copy: src={{ item }}
          dest=/opt/voc/share/
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/bgloop.ts"
      - "../../../artwork/{{ event.acronym }}/bgloop.ts"
      - "artwork/bgloop.ts"

  - name: uploading background-image
    copy: src={{ item }}
          dest=/opt/voc/share/
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/bg.png"
      - "../../../artwork/{{ event.acronym }}/bg.png"
      - "artwork/bg.png"

  - name: uploading pause-loop
    copy: src={{ item }}
          dest=/opt/voc/share/pause.ts
          owner=root group=staff mode=0644
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/pause.ts"
      - "../../../artwork/{{ event.acronym }}/pause.ts"
      - "artwork/default-pause.ts"

  - name: synchronizing default music-files
    synchronize: src={{ item }}
                 dest=/opt/voc/share/
                 delete=yes
    with_first_found:
      - "../../../artwork/{{ event.acronym }}/saal{{ room_number }}/pause-music"
      - "../../../artwork/{{ event.acronym }}/pause-music"
      - "artwork/pause-music"
