---
 - name: install additional packages for encoder role
   apt: name={{ item }} state=latest
   with_items:
    - nginx
    - libnginx-mod-rtmp
    - icecast2
    - samba
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
    - gstreamer1.0-tools
    - gstreamer1.0-vaapi
    - libgstreamer1.0-0
    - python3
    - python3-gi
    - python3-pyinotify
    - python3-sdnotify
    - python3-scipy
    - gir1.2-gstreamer-1.0
    - gir1.2-gst-plugins-base-1.0
    - rlwrap
    - fbset
    - desktopvideo
    - decklink-debugger
