---
  - name: Create apt proxy detection script
    copy: dest=/etc/apt/detect-apt-proxy.sh
          src=detect-apt-proxy.sh
          mode=0755 owner=root group=root
    tags:
      - apt

  - name: Configure apt to use proxy detection script
    lineinfile: state=present create=yes
                dest=/etc/apt/apt.conf.d/30detectproxy
                line='Acquire::http::ProxyAutoDetect "/etc/apt/detect-apt-proxy.sh";'
                regexp='^Acquire::http::ProxyAutoDetect.*'
    when: "'lan.c3voc.de' in ansible_fqdn"
    tags:
      - apt

  # Remove manual configured apt proxy stuff

  - name: Find files with manual configured apt proxies
    find: path=/etc/apt/apt.conf.d/
          contains="Acquire::http::Proxy"
    register: configured_apt_proxys
    tags:
      - apt

  - name: debug configured_apt_proxys
    debug: var=configured_apt_proxys
           verbosity=2
    tags:
      - apt

  - name: Remove manual all configured apt proxies on public hosts
    lineinfile: dest="{{ item.path }}" state=absent
                regexp="^Acquire::http::Proxy.*"
    with_items: "{{ configured_apt_proxys.files }}"
    when: "'lan.c3voc.de' not in ansible_fqdn and configured_apt_proxys.files is defined"
    tags:
      - apt

  - name: Remove manual configured apt proxies
    lineinfile: dest="{{ item.path }}" state=absent
                regexp="^Acquire::http::Proxy\ .*"
    with_items: "{{ configured_apt_proxys.files }}"
    when:  "'lan.c3voc.de' in ansible_fqdn and configured_apt_proxys.files is defined"
    tags:
      - apt
