# managed by register2ansible.pl
[relays:children]
master_relays
edge_relays

[master_relays]
live.ber.c3voc.de              nginx=yes icecast=yes

[edge_relays]
live.alb.c3voc.de              nginx=yes icecast=yes icecast_master_ip=195.54.164.164 nginx_stream_masters='["195.54.164.164"]'
live.bn.c3voc.de               nginx=yes icecast=no nginx_stream_masters='["195.54.164.164"]'
live.dus.c3voc.de              nginx=yes icecast=no nginx_stream_masters='["195.54.164.164"]'
live.fem.c3voc.de              nginx=yes icecast=yes icecast_master_ip=195.54.164.164 nginx_stream_masters='["195.54.164.164"]'
live.s11.c3voc.de              nginx=yes icecast=yes icecast_master_ip=195.54.164.164 nginx_stream_masters='["195.54.164.164"]'
live.self.c3voc.de             nginx=yes icecast=yes icecast_master_ip=195.54.164.164 nginx_stream_masters='["195.54.164.164"]'
live2.alb.c3voc.de             nginx=yes icecast=yes icecast_master_ip=195.54.164.164 nginx_stream_masters='["195.54.164.164"]'
