---
  # Install packages needed for each relay
  - name: install streaming relay dependencies
    apt: name={{ item }} state=present
    with_items:
      - oggfwd-voc
  - include: ocsp.yml

  - include: nginx.yml
  - include: icecast.yml
  - include: iptables.yml
  - include: sysctl.yml
