---
  - name: restart icecast
    service: name=icecast2-beta state=restarted
    when: icecast is defined and icecast == 'yes'

  - name: restart nginx
    service: name=nginx state=restarted
    when: nginx is defined and nginx == 'yes'

  - name: trigger register_relay
    service: name=register_relay state=restarted

  - name: reload rc.local
    command: /etc/rc.local

  - name: reload sysctl
    command: /sbin/sysctl --system

  - name: reload php-fpm
    service: name=php5-fpm state=reloaded
