pg_user: "{{ lookup('keepass', 'ansible/media/postgresql.username') }}"
pg_password: "{{ lookup('keepass', 'ansible/media/postgresql.password') }}"
elasticsearch_host: _site_
pg_listen_addresses: localhost,10.0.0.2
pg_client_net: 10.0.0.1/32
users:
  - { name: 'mm', state: 'present' }
  - { name: 'voc', state: 'present' }
  - { name: 'andi', state: 'present' }
  - { name: 'derpeter', state: 'present' }
