---
- file: path=/etc/nginx/sites-enabled/default state=absent
- file: path=/etc/nginx/sites-enabled/00-acmetool.conf state=absent

- template: src=nginx/{{ item }}
        dest=/etc/nginx/sites-available/{{ item }}
        owner=root group=root mode=0640
  with_items:
    - "mirror.ftp.media.ccc.de"

- file: src=/etc/nginx/sites-available/{{ item }}
        dest=/etc/nginx/sites-enabled/{{ item }}
        state=link
  with_items:
    - "mirror.ftp.media.ccc.de"
  notify:
    - restart nginx
