---
  # delete bin dir before deployment
  - name: Ansible delete bin directory
    file:
      path: /opt/lenovo-throttling-fix/bin/
      state: absent

  # directories & code
  - name: create lenovo-throttling-fix directories
    file: dest={{ item }} state=directory
      owner=root group=root
    with_items:
      - /opt/lenovo-throttling-fix/
      - /opt/lenovo-throttling-fix/bin/

  - name: get lenovo-throttling-latest-release-URL
    uri:
      url: https://api.github.com/repos/erpalma/throttled/releases/latest
      return_content: true
    register: github_json_response

  - name: checkout lenovo-throttling-fix latest release
    get_url:
      url: "{{ github_json_response.json.tarball_url }}"
      dest: /opt/lenovo-throttling-fix/throttled_latest.tar.gz

  - name: unpack lenovo-throttling-fix latest release
    unarchive:
      src: /opt/lenovo-throttling-fix/throttled_latest.tar.gz
      dest: /opt/lenovo-throttling-fix/bin/
      copy: no

  # lenovo-throttling-fix configuration
  - name: create lenovo-throttling-fix config
    template: src=lenovo-throttling-fix/lenovo-throttling-fix.conf.j2
              dest=/etc/lenovo_fix.conf
              mode=0644 owner=root group=root

  # lenovo-throttling-fix service
  - name: create lenovo-throttling-fix systemd-unit
    template: src=systemd-units/lenovo_fix.service.j2
              dest=/etc/systemd/system/lenovo_fix.service
              mode=0644 owner=root group=root

  - name: reload systemd daemon
    command: systemctl daemon-reload

  - name: enable & (re)start lenovo-throttling-fix service
    service: name=lenovo_fix
             enabled=yes
             state=restarted
