---
  - include: general.yml
  - include: packages.yml
  - include: slim.yml
  - include: x11vnc.yml
  - include: edid-tools.yml
  - include: voctomix.yml
    tags: encodermode
  - include: voctomix2.yml
    tags: encodermode
  - include: irssi.yml
  - include: rc.local.yml
    tags:
      - iptables
      - rclocal
