---
  # install general mixer packages
  - name: install packages required to be a mixer
    apt: name={{ item }} state=latest
    with_items:
      - chromium
      - dwm-voc
      - fonts-roboto
      - gir1.2-gst-plugins-base-1.0
      - gir1.2-gstreamer-1.0
      - gir1.2-gtk-3.0
      - gnome-themes-standard
      - gstreamer1.0-alsa
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-tools
      - gstreamer1.0-vaapi
      - irssi
      - libcairo2-dev
      - libdbus-glib-1-dev
      - libgirepository1.0-dev
      - libgstreamer1.0-0
      - lxde
      - python3
      - python3-dbus
      - python3-dev
      - python3-gi
      - python3-gi
      - python3-gi-cairo
      - python3-gi-cairo
      - python3-pyinotify
      - python3-scipy
      - python3-wheel
      - runit
      - slim
      - x11vnc
      - x11-xserver-utils
      - xserver-xorg
      - xterm
