---
nebula_version: 1.10.0
nebula_archive_checksum: "sha256:79bf98683091cceeab6333626ca6068a1f26fb34238147231c6aa5f1b73e5e23"
nebula_lighthouse: false
nebula_ca_cert: "{{ lookup('keepass', 'ansible/nebula/CA.attr_cert') }}"
nebula_lighthouses: []
nebula_hosts_map: []
