---
  # Install PHP + stuff
  - name: install streaming page packages
    apt:
      name:
        - php7.0-fpm
        - php7.0-sqlite3
        - php7.0-xml
        - libsqlite3-dev
        - sqlite3
      state: latest
    tags: install

  # Create default pool
  - name: configure php-fpm
    template: dest=/etc/php/7.0/fpm/pool.d/www.conf
              src=php_fpm/www.conf.j2
              mode=0644 owner=root group=root
    notify: reload php7.0-fpm
    tags:
      - install
      - config

  # Change php.ini settings
  - name: disable php version expose
    lineinfile: dest=/etc/php/7.0/fpm/php.ini
                regexp="expose_php.*=.*"
                line="expose_php = Off"
    notify: reload php7.0-fpm
    tags:
      - install
      - config

  - name: enable php short_open_tag
    lineinfile: dest=/etc/php/7.0/fpm/php.ini
                regexp="short_open_tag.*=.*"
                line="short_open_tag = On"
    notify: reload php7.0-fpm
    tags:
      - install
      - config

  - name: enable php short_open_tag on cli
    lineinfile: dest=/etc/php/7.0/cli/php.ini
                regexp="short_open_tag.*=.*"
                line="short_open_tag = On"
    tags:
      - install
      - config

  # Enable service
  - name: (re)start php-fpm
    service: name=php7.0-fpm enabled=yes state=restarted
    tags: install
    changed_when: false
