---
- name: Change sysctl settings
  ansible.builtin.copy:
    dest: /etc/sysctl.d/loadbalancer.conf
    src: ../../../roles/relay/files/sysctl/relay.conf
    mode: "0644"
    owner: root
    group: root
  notify: reload sysctl

- name: Increase softlimit for open files
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    create: true
    regexp: '\*.*soft.*nofile.*\d+$'
    state: present
    line: "*               soft    nofile 4092"
    insertbefore: ".*End.*file$"
    mode: "0644"
