---
- name: Install acmetool package (Debian/Binary)
  block:
  - shell: /usr/local/bin/go get github.com/hlandau/acme/cmd/acmetool
    environment:
      GOPATH: /usr/local
      GOPROXY: https://proxy.golang.org
  tags: acmetool-install

- file:
    name: /var/lib/acme/conf
    state: directory
  tags: acmetool-install

- name: create response file
  template: src=response-file.yml.j2
            dest=/var/lib/acme/conf/responses
            mode=0644 owner=root group=root
  tags: acmetool-install
  vars:
    acmetool_responses_method: listen

- name: run quickstart
  command: acmetool quickstart
  tags: acmetool-install

- name: "acmetool: want"
  command: "acmetool want {{ item }}"
  loop: "{{ acmetool_want }}"
  tags: acmetool-websrv
  when: acmetool_want is defined

- name: create response file
  template: src=response-file.yml.j2
            dest=/var/lib/acme/conf/responses
            mode=0644 owner=root group=root
  tags: acmetool-install
  vars:
    acmetool_responses_method: webroot
