---
  ############
  # collectd #
  ############
  # libvirtd
  - shell: "command -v libvirtd"
    register: libvirtd_bin
    changed_when: false
    ignore_errors: yes

  - name: install collectd config file
    template: dest=/etc/collectd/collectd.conf
              src=collectd/collectd.client.conf.j2
              owner=root group=root mode=0640
    notify: restart collectd
    tags:
      - install
      - config

  - name: install collectd perl packages
    apt: name={{ packages|flatten(levels=1) }} state=latest
    vars:
      packages:
        - collectd
        - liblwp-protocol-https-perl
        - libxml-simple-perl
    tags: install

  - name: create plugins directory
    file: dest=/opt/voc/collectd/plugins/Collectd/Plugins
          state=directory
    tags: install

  - name: create custom types.db
    file: dest=/opt/voc/collectd/types.db state=touch
    notify: restart collectd
    changed_when: false
    tags: install

  - name: add icecast2 collectd plugin
    template: dest=/opt/voc/collectd/plugins/Collectd/Plugins/Icecast2.pm
              src=collectd/plugins/Icecast2.pm
    notify: restart collectd
    when: icecast is defined and icecast == 'yes' and inventory_hostname in groups['relays']
    tags: install

  - name: add haproxy collectd plugin
    template: dest=/opt/voc/collectd/plugins/haproxy.py
              src=collectd/plugins/haproxy.py
    notify: restart collectd
    when: haproxy is defined and haproxy
    tags: install

  - name: adding entries for curl_json php to types.db
    lineinfile: dest=/opt/voc/collectd/types.db
                regexp="{{ item.regex }}"
                line="{{ item.line }}"
    with_items:
      - { regex: '^listen_queue\ .*', line: 'listen_queue       value:GAUGE:0:65535' }
      - { regex: '^active_processes\ .*', line: 'active_processes   value:GAUGE:0:65535' }
      - { regex: '^total_processes\ .*', line: 'total_processes    value:GAUGE:0:65535' }
    notify: restart collectd
    when: php is defined and php != 'no'
    tags:
      - install
      - config

  # TODO: remove me
  - name: adding entries to types.db
    lineinfile: dest=/usr/share/collectd/types.db
                regexp="{{ item.regex }}"
                line="{{ item.line }}"
                state=absent
    with_items:
      - { regex: '^listen_queue\ .*', line: 'listen_queue       value:GAUGE:0:65535' }
      - { regex: '^active_processes\ .*', line: 'active_processes   value:GAUGE:0:65535' }
      - { regex: '^total_processes\ .*', line: 'total_processes    value:GAUGE:0:65535' }
    notify: restart collectd
    when: nginx is defined and nginx != 'no'
    tags:
      - install
      - config

  - include: snmp.yml
    when: ansible_hostname is match('mixer\d+')
