---
  ############
  # collectd #
  ############
  # libvirtd
  - shell: "command -v libvirtd"
    register: libvirtd_bin
    changed_when: false
    ignore_errors: yes

  - name: install collectd perl packages
    apt: name={{ item }} state=latest
    with_items:
      - collectd
      - liblwp-protocol-https-perl
      - libxml-simple-perl
    tags: install

  - name: create plugins directory
    file: dest=/opt/voc/collectd/plugins/Collectd/Plugins
          state=directory
    tags: install

  - name: create custom types.db
    file: dest=/opt/voc/collectd/types.db state=touch
    notify: restart collectd
    changed_when: false
    tags: install

  - name: add icecast2 collectd plugin
    template: dest=/opt/voc/collectd/plugins/Collectd/Plugins/Icecast2.pm
              src=collectd/plugins/Icecast2.pm
    notify: restart collectd
    when: icecast is defined and icecast == 'yes'
    tags: install

  - name: add nginx rtmp collectd plugin
    template: dest=/opt/voc/collectd/plugins/Collectd/Plugins/NginxRtmp.pm
              src=collectd/plugins/NginxRtmp.pm
    notify: restart collectd
    when: rtmp is defined and rtmp
    tags: install

  - name: add nginx hls collectd plugin
    template: dest=/opt/voc/collectd/plugins/NginxHls.py
              src=collectd/plugins/NginxHls.py
    notify: restart collectd
    when: nginx is defined and nginx
    tags: install

  - name: add nginx dash collectd plugin
    template: dest=/opt/voc/collectd/plugins/NginxDash.py
              src=collectd/plugins/NginxDash.py
    notify: restart collectd
    when: nginx is defined and nginx
    tags: install

  - name: add haproxy collectd plugin
    template: dest=/opt/voc/collectd/plugins/haproxy.py
              src=collectd/plugins/haproxy.py
    notify: restart collectd
    when: haproxy is defined and haproxy
    tags: install

  - name: install collectd config file
    template: dest=/etc/collectd/collectd.conf
              src=collectd/collectd.client.conf.j2
              owner=root group=root mode=0640
    notify: restart collectd
    tags:
      - install
      - config

  - name: adding entries for curl_json php to types.db
    lineinfile: dest=/opt/voc/collectd/types.db
                regexp="{{ item.regex }}"
                line="{{ item.line }}"
    with_items:
      - { regex: '^listen_queue\ .*', line: 'listen_queue       value:GAUGE:0:65535' }
      - { regex: '^active_processes\ .*', line: 'active_processes   value:GAUGE:0:65535' }
      - { regex: '^total_processes\ .*', line: 'total_processes    value:GAUGE:0:65535' }
    notify: restart collectd
    when: php is defined and php != 'no'
    tags:
      - install
      - config

  # TODO: remove me
  - name: adding entries to types.db
    lineinfile: dest=/usr/share/collectd/types.db
                regexp="{{ item.regex }}"
                line="{{ item.line }}"
                state=absent
    with_items:
      - { regex: '^listen_queue\ .*', line: 'listen_queue       value:GAUGE:0:65535' }
      - { regex: '^active_processes\ .*', line: 'active_processes   value:GAUGE:0:65535' }
      - { regex: '^total_processes\ .*', line: 'total_processes    value:GAUGE:0:65535' }
    notify: restart collectd
    when: nginx is defined and nginx != 'no'
    tags:
      - install
      - config

  - name: install snmp stuff
    apt: name={{ item }} state=present
    with_items:
      - snmp
      - snmp-mibs-downloader
    when: ansible_hostname | match('mixer\d+')
