---
 - include: repos.yml
 - include: packages.yml
 - include: sudo.yml
 - include: user.yml user=voc
 - include: user.yml user=andi
 - include: user.yml user=derpeter
 - include: user.yml user=florolf
 - include: user.yml user=mazdermind
 - include: user.yml user=meise

 - name: Add all SSH keys to voc user
   authorized_key: user=voc manage_dir=true key="{{ lookup('file', item) }}" state=present
   with_fileglob:
    - user/*/authorized_keys
