---
  - include: repos.yml
  - include: packages.yml
  - include: vim.yml
  - include: sudo.yml
  - include: grub.yml
    when: grub != 'no'
  - include: ntp.yml
    when: ansible_virtualization_type != 'lxc'
  - include: inittab.yml
  - include: molly-guard.yml
  # realise users
  - include: user.yml user=voc
  - include: user.yml user=andi
  - include: user.yml user=derpeter
  - include: user.yml user=florob
  - include: user.yml user=florolf
  - include: user.yml user=mazdermind
  - include: user.yml user=meise

  - name: setting voc password
    user: name=voc
          password={{ user_voc_password | default('$6$xQDo3Tyf$q8mxcBQTKmaGUA2cHuCS0QoeHSyYwESkyq/53OmEYLErMWF.CpS9Q3NzAoeB3zntZBpysfmEQ9r6sLjubLq5F1') }}

  - name: add all SSH keys to voc user
    authorized_key: user=voc manage_dir=true key="{{ lookup('file', item) }}" state=present
    with_fileglob:
      - user/*/authorized_keys

  # Modify message of the day
  - name: adding message of the day
    template: dest=/etc/motd
              src=motd/motd
              owner=root group=root mode=0644
