---
  # Setting vim as default editor
  - name: vim is our editor
    alternatives: name=editor path=/usr/bin/vim.basic

  # Adding content to files
  - name: enable syntax highlighting in vim
    lineinfile: dest=/etc/vim/vimrc state=present regexp='^syntax '
                line='syntax on'

  - name: enable dark background in vim
    lineinfile: dest=/etc/vim/vimrc state=present regexp='^set background'
                line='set background=dark'
