hostname = "10.73.97.3"
groups = ["debian-bookworm"]

[metadata]
hostname = "encoderc4.labor.koeln.ccc.de"

[metadata.crs-worker.secrets]
encoding.secret = "!decrypt:encrypt$gAAAAABmhFbnelqRLAIVSSoulff5VhTMF4VwNWcQY1lFykx6ZBBKt7fgUJ1wK8N0koDCWdvpYv1njZCbX0czS9yG2k6lG1xKk7vcE8gbU8Lb7dAc-14Vv86rix8qIzk4cx482sRbzi7a"
encoding.token = "!decrypt:encrypt$gAAAAABmhFbQ3RlhXKPjsmdxSQoHhjvIVrnFkFto_Kzq3utVXGTEDwTj8HcX1RqZGwETlkMz6iQOzAXsk3facY7u0BcQh3agDrqFeh7Sdg2wrodWgWqMJD99dOEnSM56HDccdFfdEuNI"

[metadata.event]
room_name = "HS8"

[metadata.interfaces.eth0]
ips = ["172.23.23.118/23", "10.73.97.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABmhFXnPeqkBp1Q_dlLSCwub0LBbEro4zbFCihoenJiKlDAI8cDDN5uNOA8M4rgTMkSgEMLGGt7-sSbqzDTbUUIqOMSn51fZZRIfvU-reVtWMy5cnI="

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080i50"

[metadata.voctocore.sources.slides]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
