hostname = "10.73.7.3"
groups = ["debian-buster"]

[metadata.crs-worker]
token.encoding = "nope"
secret.encoding = "nope"

[metadata.event]
room_name = "GLT23"

[metadata.interfaces.eth0]
ips = [
    "192.168.28.24/24",
    "10.73.7.3/16",
]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABkOR_vdc1TC6Hkh0TtmqahIXdc324x7ZRLqhaLWAozWTcm7f7Z-jeWiv0Ugc2KJ9yPqVhxLib-hsGEWPyLSRUavPg2yjK658sTf0WW9TgXEJpoB4Q="

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 2
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
