groups = ["debian-buster"]

[metadata.crs-worker.secrets.encoding]
token = "!kee_user:ansible|worker-groups|encoder191"
secret = "!kee_pass:ansible|worker-groups|encoder191"

[metadata.event]
room_name = "Saal 191"

[metadata.interfaces.eth0]
ips = ["10.73.191.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABkNYlWopNOi_avhwhjvt5SiLmuKIV3HxxkgW3-Qys9ld6a9g1ozQKj7Jvie3_5_oLewa18snIb4GnlvdXoGiCnNGrlFyQgR7_UvIgYD-XGF015kR4="

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 5
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
