groups = ["debian-bookworm"]

[metadata.crs-worker.secrets]
encoding.secret = "!kee_pass:ansible|worker-groups|encoder-osc1"
encoding.token = "!kee_user:ansible|worker-groups|encoder-osc1"
#meta.secret = "!kee_pass:ansible|worker-groups|encoder-osc1-meta"
#meta.token = "!kee_user:ansible|worker-groups|encoder-osc1-meta"

[metadata.event]
room_name = "Saal"

[metadata.interfaces.eth0]
ips = ["10.73.41.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABkZ3SZDZReq48XFExoLOUvnyf4PO_mY9x-dvpdkkIqcfFte2lPcohXv0e-v2BPfMezv8l7S34EgXP1DEB6IaBLThtHwbJILKVAWCWvd__hmyZwB4o="

[metadata.voctocore.sources.cam1]
devicenumber = 1
mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 0
mode = "1080p25"
hdmi = true

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
