bundles = []
groups = ["debian-bookworm"]

[metadata.apt.packages.alsa-utils]
[metadata.apt.packages."gstreamer1.0-alsa"]
[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.i965-va-driver]
[metadata.apt.packages.v4l-utils]

[metadata.grub]
efi = true

[metadata]
nameservers = ["1.1.1.1"]

[metadata.crs-worker.secrets]
encoding.secret = "!decrypt:encrypt$gAAAAABo1XfP2klLPEbDNpKS9Fb3MA8eQn9oVNaZJzN_GhUDuP2MjLM3svQ_4l1Gg8i544EZZjeanSfAb4SsCm9p6YwgEO0QVnp5QFX59TIn8gWXizH4HzLljFQFEaUuCWpbCRNP1lnX"
encoding.token = "!decrypt:encrypt$gAAAAABo1Xe5sFJb7wXWRqLZG3BuwauAsozX0aG4ZrysqHtlOhOZP-key3rN6JiGypxlt5sspaWHZhuW-IhgOMtAnmWzU62UC0k-891jRALLTDYbdtP6ZFFeQv3M4n2AcWtsclgZwigO"
meta.secret = "!decrypt:encrypt$gAAAAABo1b-uODrFu7e_4BGVDyqioyPlQ4CcjxeMZAzLrYg7tHLhaYUdhwOI3c9Ho1kJ1KTEMhsLRmpc1UKc8kbZ9OShG_4TnhcRp-yqB5t3e0ifcx4e3nDLjcUy6dYd_mj90QWSkkpO"
meta.token = "!decrypt:encrypt$gAAAAABo1b-mM8ZUb3OjY8RbOG-pjJh028T-4vwW_GQeuXLDvq4FfjX8XiDsXP2xTYI9Jw-dtjaQ_XUGJmdM8quUEiC94kSdaNJBAciXCWd6OSxyoCLq35WJZAwTQODNtRtJ_6ioY-MD"

[metadata.event]
room_name = "LoTHR"

[metadata.interfaces.eth0]
ips = [
    "10.73.28.3/16",
#    "192.168.69.202/24", # realraum
    "192.168.0.209/23", # testing
]

# gateway4 = "192.168.69.254" # realraum
gateway4 = "192.168.0.1" # testing

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABo1XfkhnE3utcKFqchfqfY6YMMJAaJoL-X43HvlJQG3XC4SUJTKqKtgfa2EY6AVABaaF0oCVBMdTt9lPhOf2k1hjzTLtt0zXpjB9bvKzsa3WzYgqE="
parallel_slide_streaming = false
parallel_slide_recording = true
vaapi = true
mirror_view = false
enable_sbs_presets_for_multi_camera = false

# INFO FOR CAMERA
# Ensure the camera outputs 1080p
# Sony: Menu -> Setup -> External Output -> HDMI Output Settings -> Resolution -> 1080p

[metadata.voctocore.sources.cam1]
kind = "v4l2"
device= "/dev/v4l/by-id/usb-MACROSILICON_UGREEN_15389_20230204-video-index0"
width = "1920"
height = "1080"
framerate = "30/1"
format = "YUY2"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "audio"

[metadata.voctocore.sources.audio]
kind = "alsa"
device = "hw:CARD=U15389,DEV=0"

# BEFORE YOU TOUCH THIS BECAUSE VOCTOCORE DOESNT START, CHECK IF THE EXTRON OUTPUTS 1080p25!!!

[metadata.voctocore.sources.slides]
kind = "v4l2"
device = "/dev/v4l/by-id/usb-Elgato_Game_Capture_HD60_S+_0004EE8273000-video-index0"
width = "1920"
height = "1080"
framerate = "60/1" # THIS MUST MATCH THE EXTRON OUTPUT
format = "YUY2"
