groups = ["debian-bookworm"]

[metadata.crs-worker.secrets]
encoding.secret = "!decrypt:encrypt$gAAAAABkOS_by1-OF4v0BuFqOwofXy4ka7cp5v7UQjxjrvQasQbmx4p4W4ZYPu0GyZwWvIzJdR0gUymexb-2QrzJAMD1fZd3p3BZQmHOlFulwegjXZIyKYo3SsgTnt9NsnSzYqNBNclY"
encoding.token = "!decrypt:encrypt$gAAAAABkOS_Us1SxDDO0JZGgPQ7g-VMCw792NVYP2-k8wY5okEnlD_OWTePmEIbF6RK0h2tHZ9bRV_ReRPRLH3GPIsDA_49YaRQYoxzTQUkFOkEin9LQDiGsyAFfMtS5bP42Sfc3k8DT"

[metadata.event]
room_name = "HS i13"

[metadata.interfaces.eth0]
ips = ["10.73.28.3/16"]
gateway4 = "10.73.0.254"

[metadata.voctocore]
streaming_auth_key = "!decrypt:encrypt$gAAAAABmAZJ67a2kB2s4d-oDslJTFVUp8H7Zm5ePu6cJZX3OyHoV-yteKgw24aZVAusKnkh8wwEeUZoZ_rbdD6OU4DNdc08RWEZ8VLRfnJT0z-7nZ3GCKnA="

[metadata.voctocore.sources.cam1]
devicenumber = 0
mode = "1080p25"

[metadata.voctocore.sources.slides]
devicenumber = 1
mode = "1080p25"

[metadata.voctocore.audio.original]
streams = "0+1"
input = "cam1"
