groups = ["debian-trixie"]
bundles = ["loudness-rendering", "voctocore-artwork"]

[metadata]
nameservers = ["10.73.254.201"]

[metadata.interfaces.ens18]
ips = ["10.73.254.64/24"]
gateway4 = "10.73.254.201"

[metadata.loudness-rendering]
from_encoders = [
    "encoder1",
    "encoder2",
    "encoder3",
    "encoder4",
    "encoder5",
    "encoder6",
]
