groups = ["debian-bookworm", "servercase"]
bundles = ["loudness-rendering", "voctocore-artwork"]

[metadata.interfaces.ens18]
ips = ["10.73.200.98/16"]
gateway4 = "10.73.0.254"

[metadata.loudness-rendering]
from_encoders = [
    "encoder3",
    "encoder4",
    "encoder5",
]
