groups = ["debian-buster"]
bundles = ["cifs-client"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|minion4"
secret.encoding = "!kee_pass:ansible|worker-groups|minion4"

[metadata.interfaces.eth0]
ips = ["10.73.4.7/16"]
gateway4 = "10.73.0.254"

[metadata.cifs-client.mounts.video]
serverpath = "//10.73.128.101/video"

[metadata.cifs-client.mounts.video-encoded]
serverpath = "//10.73.128.101/encoded"

[metadata.cifs-client.mounts.video-fuse]
serverpath = "//10.73.128.101/fuse"

[metadata.cifs-client.mounts.video-tmp]
serverpath = "//10.73.128.101/tmp"
