groups = ["debian-bookworm"]

[metadata.crs-worker.secrets.encoding]
token = "!kee_user:ansible|worker-groups|minion4"
secret = "!kee_pass:ansible|worker-groups|minion4"

[metadata.interfaces.br0]
ips = ["10.73.4.7/16"]
gateway4 = "10.73.0.254"

[[metadata.zfs.pools.zroot.when_creating.config]]
type = "mirror"
devices = [
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2421E8B25852_1-part4",
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2423E8B7C367_1-part4",
]

[metadata.crs-worker]
number_of_encoding_workers = 2
room_name = "Galerie"
use_vaapi = true
