groups = ["debian-buster"]

[metadata.crs-worker.secrets.encoding]
token = "!kee_user:ansible|worker-groups|minion1"
secret = "!kee_pass:ansible|worker-groups|minion1"

[metadata.interfaces.eth0]
ips = ["10.73.1.7/16"]
gateway4 = "10.73.0.254"
