groups = ["debian-bookworm"]
#bundles = ["loudness-local", "voctocore-artwork"]

[metadata.crs-worker.secrets.encoding]
token = "!kee_user:ansible|worker-groups|minion3"
secret = "!kee_pass:ansible|worker-groups|minion3"

[metadata.interfaces.br0]
ips = ["10.73.3.7/16"]
gateway4 = "10.73.0.254"

[[metadata.zfs.pools.zroot.when_creating.config]]
type = "mirror"
devices = [
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2420E8AEBB81_1-part4",
  "/dev/disk/by-id/nvme-CT4000P3PSSD8_2423E8B7C390_1-part4",
]

[metadata.loudness-rendering]
from_encoders = [
    "encoder3",
    "encoder4",
]
