groups = ["debian-buster"]
bundles = ["cifs-client"]

[metadata.crs-worker]
token.encoding = "!kee_user:ansible|worker-groups|minion2"
secret.encoding = "!kee_pass:ansible|worker-groups|minion2"

[metadata.interfaces.eth0]
ips = ["10.73.2.7/16"]
gateway4 = "10.73.0.254"
