bundles = ["thinkfan"]
groups = ["debian-bookworm"]

[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.i965-va-driver]

[metadata.interfaces.eth0]
#ips = ["10.73.96.1/16"]
dhcp = true

[metadata.voctomix2]
rev = "preset_toolbar"

[metadata.mixer-common]
enable-irssi = false

[metadata.voctogui]
high_dpi = false
