hostname = "10.73.96.1"
bundles = ["thinkfan"]
groups = ["debian-bookworm"]

[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.i965-va-driver]

[metadata.interfaces.eth0]
ips = ["10.73.96.1/16"]
dhcp = true

[metadata.mixer-common]
enable-irssi = false

[metadata.pygtk-atem-switcher.atem]
ip = "10.73.191.40"
settings.inputs.input1 = "In1"
settings.inputs.input2 = "In2"
settings.inputs.input3 = "In3"

[metadata.voctomix2]
rev = "main"

[metadata.voctogui]
high_dpi = false
vaapi = true
