bundles = ["pygtk-atem-switcher", "thinkfan"]
groups = ["debian-bookworm"]

[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.i965-va-driver]

[metadata.interfaces.eth0]
ips = ["10.73.2.1/16"]
gateway4 = "10.73.0.254"

[metadata.pygtk-atem-switcher.atem.settings.inputs]
# use "x" to hide the button in the UI
input1 = "Laptop"
input2 = "Doc Cam"
input3 = "x"
input4 = "info-beamer"
