bundles = ["pygtk-atem-switcher", "thinkfan"]
groups = ["debian-buster"]

[metadata.interfaces.eth0]
ips = ["10.73.2.1/16"]
gateway4 = "10.73.0.254"

[metadata.pygtk-atem-switcher.atem]
video_mode = "1080p25"

[metadata.pygtk-atem-switcher.atem.settings.inputs]
input1 = "Laptop"
input2 = "External"
input4 = "info-beamer"
