bundles = ["pygtk-atem-switcher", "thinkfan"]
groups = ["debian-bookworm"]

[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.i965-va-driver]

[metadata.interfaces.eth0]
ips = ["10.73.1.1/16"]
gateway4 = "10.73.0.254"

[metadata.pygtk-atem-switcher.atem.settings.inputs] # these are defaults
input1 = "Moderation"
input2 = "Kids"
