bundles = []
groups = ["debian-bookworm"]

# required if vaapi is activated in voctocore
[metadata.apt.packages."gstreamer1.0-libav"]

[metadata]
nameservers = ["1.1.1.1"]

[metadata.interfaces.eth0]
ips = [
    "10.73.28.1/16",
#    "192.168.69.201/24", # realraum
    "192.168.0.208/23", # testing
]

#gateway4 = "192.168.69.254" # realraum
gateway4 = "192.168.0.1" # testing

[metadata.voctogui]
high_dpi = false
vaapi = false
