bundles = ["pygtk-atem-switcher", "thinkfan"]
groups = ["debian-bookworm"]

[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.i965-va-driver]

[metadata.interfaces.eth0]
ips = ["10.73.1.1/16"]
gateway4 = "10.73.0.254"

[metadata.voctomix2]
rev = "2.3"

[metadata.voctogui]
vaapi = true

[metadata.pygtk-atem-switcher.atem.settings.inputs]
# use "x" to hide the button in the UI
input1 = "LAPTOP 1"
input2 = "HDMI 2"
input3 = "x"
input4 = "info-beamer"
