---
- name: Deploy stream ingest servers
  hosts: ingest
  roles:
    - { role: common, tags: ['common'] }
    - { role: monitoring-client, tags: ['monitoring'] }
    - role: nginx
      tags: nginx
    - role: letsencrypt
      vars:
        domain: "{{ ansible_fqdn }}"
      tags: letsencrypt
    - role: consul
      tags: [consul]
    - role: icecast
      vars:
        icecast_push_master: true
      tags: icecast
    - { role: ingest, tags: ['ingest'] }
