---
  - import_playbook: encoders.yml
  - import_playbook: mixers.yml
  - import_playbook: relays.yml
  - import_playbook: servers.yml
  - import_playbook: loadbalancers.yml
  - import_playbook: minions.yml
  - import_playbook: tracker.yml
  - import_playbook: transcoders.yml
  - import_playbook: audio-pis.yml
  - import_playbook: web.c3voc.de.yml
  - import_playbook: monitoring.c3voc.de.yml
  - import_playbook: build.c3voc.de.yml
  - import_playbook: mng.c3voc.de.yml
