---
  - include: encoders.yml
  - include: mixers.yml
  - include: backup-recorders.yml
  - include: relays.yml
  - include: servers.yml
  - include: loadbalancers.yml
  - include: minions.yml
  - include: tracker.yml
  - include: transcoders.yml
  - include: audio-pis.yml
  - include: web.c3voc.de.yml
  - include: monitoring.c3voc.de.yml
  - include: build.c3voc.de.yml
  - include: mng.c3voc.de.yml
