subgroups = [
    "saal1",
    "saal2",
    "saal3",
    "saal4",
    "saal5"
    "saal6",
    "saal191",
    "servercase",
]

[metadata.event]
timezone = "Europe/Berlin"
name = "Chaos Communication Camp 2023"
slug = "camp2023"
