bundles = ["samba", "snmp-temperature-monitoring", "zfs"]

[metadata.apt.packages.intel-media-va-driver-non-free]
[metadata.apt.packages.firmware-misc-nonfree]

[metadata.crs-worker]
number_of_encoding_workers = 2
CPUAffinity = "0-11"
separate_vaapi_worker = true

[metadata.grub]
efi = true

[metadata.systemd-networkd.bridges.br0]
match = ["enp87s0", "enp90s0", "enp2s0f0", "enp2s0f1"]

[metadata.users.voc]
groups = ["render", "video"]

[metadata.zfs.datasets.zroot]

[metadata.zfs.datasets."zroot/ROOT"]

[metadata.zfs.datasets."zroot/ROOT/debian"]
mountpoint = "/"

[metadata.zfs.datasets."zroot/home"]
mountpoint = "/home"

[metadata.zfs.datasets."zroot/home/root"]
mountpoint = "/root"

[metadata.zfs.datasets."zroot/var"]

[metadata.zfs.datasets."zroot/var/cache"]
mountpoint = "/var/cache"

[metadata.zfs.datasets."zroot/var/lib"]
mountpoint = "/var/lib"

[metadata.zfs.datasets."zroot/var/log"]
mountpoint = "/var/log"

[metadata.zfs.pools.zroot]
