subgroups = ["saal5", "saal6"]
members = ["releasing", "loudness-rendering"]

[metadata.event]
name = "DENOG17"
slug = "denog17"
schedule_json = "https://pretalx.com/denog17/schedule/export/schedule.json"
