subgroups = ["saal2", "saal3", "saal5", "servercase"]

[metadata.event]
timezone = "Europe/Berlin"
name = "easterhegg 2024"
slug = "eh21"
overlays = "https://webdump.sophies-kitchen.eu/eh21/overlays.tar.gz"
schedule_xml = "https://data.c3voc.de/eh21/everything.schedule.xml"
