subgroups = ["saal1", "saal2", "saal3", "saal4", "saal5", "saal6", "saalc4", "servercase"]
members = ["releasing"]

[metadata.event]
name = "FrOSCon 2025"
slug = "froscon2025"
schedule_json = "https://programm.froscon.org/2025/schedule.json"

[metadata.voctocore]
enable_sbs_presets_for_multi_camera = false
