
subgroups = ["saal1", "saal2", "saal3", "saal4", "saal94", "servercase"]
members = ["releasing"]

[metadata.event]
name = "WHY2025"
slug = "why2025"

schedule_json = "https://program.why2025.org/why2025/schedule/export/schedule.json"
