---
# use consul in server mode
consul_server: false

# enable consul webui on http port
consul_ui: false

consul_arch: amd64
consul_version: 1.22.2
consul_checksum: "sha256:e9ad339128e396238f053269bf8f76aeba1b5fada6f6cb60ab19fe70e133acde"
consul_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_{{ consul_arch }}.zip"
